### ISSUE TITLE
Bit.ly links in Readme.me

### ISSUE THREAD

**Issue by cokelly** [juliasilge/deming2018#1]
Hi, both the bit.ly links to the presentations result in a 'Page Not Found' error from bit.ly.

**Comment by juliasilge** [comment]
Thanks for the note @cokelly! GitHub was having an outage, and for a while they weren't serving Pages, which meant that I couldn't set up my bit.ly links. All is back to normal now, though!

**Comment by cokelly** [comment]
Thanks!
